name: ci

on: [push, pull_request]
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
    
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: Build
        run: cargo build --all --verbose
      - name: Tests
        run: cargo test --all --verbose
      - name: Fmt
        run: cargo +nightly fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all -- -D warnings
        
  cover:
    name: Test cover
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install grcov
        run: cargo install grcov
      - name: Run grcov
        env:
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
          RUSTDOCFLAGS: "-Cpanic=abort"
          CARGO_INCREMENTAL: 0
        run: >
          cargo build;
          cargo test;
          grcov ./target/debug/ -s . -t lcov --llvm --ignore-not-existing  --ignore *.cargo/*  --ignore *core*  --ignore *std*  --ignore *alloc/*  --ignore *rustup*  --ignore *_test*  --ignore *src/ast.rs*  -o lcov.info
          
      - name: Push grcov results to Coveralls via GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "lcov.info"
